show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

title: GBot 7.0
description:
github:
  is_project_page: true
  repository_url: https://github.com/cgoulart35/GBot-Docs
  repository_name: GBot-Docs
  owner_url: https://github.com/cgoulart35
  owner_name: cgoulart35
patreon_url: https://www.patreon.com/StormerG
gbot_host: https://api.stormerg.com